"""empty message

Revision ID: 3cdcbebd2eed
Revises: 911ac8693918
Create Date: 2025-07-25 10:39:26.750681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdcbebd2eed'
down_revision = '911ac8693918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_user_fkey', 'favorites', ['user'], ['id'])

    # ### end Alembic commands ###
