"""empty message

Revision ID: 6bbb7787fce4
Revises: 365f737ec76c
Create Date: 2025-08-01 09:43:57.969274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbb7787fce4'
down_revision = '365f737ec76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.drop_column('planets_id')
        batch_op.drop_column('characters_id')

    # ### end Alembic commands ###
