"""empty message

Revision ID: 911ac8693918
Revises: eb307330a24a
Create Date: 2025-07-25 10:39:06.466897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911ac8693918'
down_revision = 'eb307330a24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'favorites', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
