"""empty message

Revision ID: b3106b7b81c9
Revises: 7f5b5937bdba
Create Date: 2025-07-28 10:31:55.129062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3106b7b81c9'
down_revision = '7f5b5937bdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_favorite_fkey', type_='foreignkey')
        batch_op.drop_column('favorite')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_favorite_fkey', type_='foreignkey')
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planets_favorite_fkey', 'favorites', ['favorite'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('characters_favorite_fkey', 'favorites', ['favorite'], ['id'])

    # ### end Alembic commands ###
