"""empty message

Revision ID: b48bda6e6250
Revises: 3cdcbebd2eed
Create Date: 2025-07-25 10:44:02.956323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48bda6e6250'
down_revision = '3cdcbebd2eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorite'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorite'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
