"""empty message

Revision ID: eb307330a24a
Revises: 10d6a6baf7f0
Create Date: 2025-07-25 10:37:08.694798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb307330a24a'
down_revision = '10d6a6baf7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['homeworld'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('homeworld')

    op.drop_table('favorites')
    # ### end Alembic commands ###
