"""empty message

Revision ID: ebcd10221f2a
Revises: 3fc150a9f416
Create Date: 2025-07-25 11:01:41.438782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcd10221f2a'
down_revision = '3fc150a9f416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('favorite',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('favorite',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
